import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const minecraftFont = localFont({
    src: "../fonts/minecraft/minecraft_0.ttf",
    variable: "--font-minecraft",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${minecraftFont.variable} antialiased`}
      >
        <div className={"relative font-minecraft bg-cover bg-no-repeat w-screen min-h-screen flex flex-col items-center overflow-hidden"}>
          <video src={"/bgs/panorama.mp4"} className={"absolute top-0 left-0 min-w-screen min-h-screen object-cover"} playsInline muted loop autoPlay/>
          {children}
        </div>
      </body>
    </html>
  );
}
